### ISSUE TITLE
simple compatibility fix for node v4

### ISSUE THREAD

**Issue by jcpst** [FGRibreau/gron#6]
Right now, trying to run with node v4 fails as follows:

```
let d = '';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

adding `use strict;` right after the shebang fixes this.

**Comment by FGRibreau** [comment]
As specified in package.json,

```
  "engines": {
    "node": ">=6"
  },
```

Node v4 is not supported, however, if this simple fix helps why not but I won't change the code to support it manually :)

/cc @kfarst
